### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by pepa65** [timsneath/dart_console#17]
Sorry, beginner's question. I got the code for kilo.dart, but I can't seem to build it. Do I have to put the code for dart_console somewhere manually? Where??

**Comment by erf** [comment]
Add a `pubspec.yaml` with `dart_console` as a `dependency`, then run `pub get`, before running `dart kilo.dart`.

minimal pubspec.yaml:

```yaml
name: kilo
dependencies:
  dart_console:
```

**Comment by pepa65** [comment]
Got it working with `pubspec.yaml`:
```yaml
name: kilo
dependencies:
  dart_console: ^0.6.0
```
And then `pub get` followed by `dart2native kilo.dart -o kilo`
Thanks for your help.
